-- Account presets table (bank names, e-wallets, etc.)
CREATE TABLE IF NOT EXISTS public.account_presets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('bank', 'ewallet', 'cash', 'savings', 'investment', 'other')),
  icon TEXT DEFAULT 'wallet',
  color TEXT DEFAULT '#9AB17A',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.account_presets (name, type, icon, color, sort_order) VALUES
  -- Banks
  ('Bank Jatim', 'bank', 'landmark', '#9AB17A', 1),
  ('BNI', 'bank', 'landmark', '#F7931E', 2),
  ('BRI', 'bank', 'landmark', '#00529C', 3),
  ('BCA', 'bank', 'landmark', '#003D79', 4),
  ('Mandiri', 'bank', 'landmark', '#003366', 5),
  ('BSI', 'bank', 'landmark', '#00A650', 6),
  ('Bank Syariah Indonesia', 'bank', 'landmark', '#00A650', 7),
  ('CIMB Niaga', 'bank', 'landmark', '#7B0E24', 8),
  ('Danamon', 'bank', 'landmark', '#FDDA24', 9),
  ('Permata', 'bank', 'landmark', '#00A3A1', 10),
  ('BTN', 'bank', 'landmark', '#F7941E', 11),
  ('Bukopin', 'bank', 'landmark', '#004B93', 12),
  ('OCBC NISP', 'bank', 'landmark', '#005BAA', 13),
  ('Panin Bank', 'bank', 'landmark', '#003B71', 14),
  ('UOB', 'bank', 'landmark', '#0033A0', 15),
  ('Maybank', 'bank', 'landmark', '#003066', 16),
  ('Muamalat', 'bank', 'landmark', '#006633', 17),
  ('Bank Mega', 'bank', 'landmark', '#003B6F', 18),
  ('Bank Sinarmas', 'bank', 'landmark', '#FDB813', 19),
  ('Digibank', 'bank', 'landmark', '#EE1D52', 20),
  ('Jenius', 'bank', 'landmark', '#00C4CC', 21),
  ('Neo Commerce', 'bank', 'landmark', '#7C3AED', 22),
  ('SeaBank', 'bank', 'landmark', '#00B4D8', 23),
  ('Allo Bank', 'bank', 'landmark', '#6366F1', 24),
  -- E-Wallets
  ('GoPay', 'ewallet', 'smartphone', '#00AED6', 100),
  ('OVO', 'ewallet', 'smartphone', '#4C3494', 101),
  ('ShopeePay', 'ewallet', 'smartphone', '#EE4D2D', 102),
  ('DANA', 'ewallet', 'smartphone', '#108EE9', 103),
  ('LinkAja', 'ewallet', 'smartphone', '#E8272C', 104),
  ('Flazz BCA', 'ewallet', 'credit-card', '#003D79', 105),
  ('e-Money Mandiri', 'ewallet', 'credit-card', '#003366', 106),
  ('BRIZZI', 'ewallet', 'credit-card', '#00529C', 107),
  ('TapCash BNI', 'ewallet', 'credit-card', '#F7931E', 108),
  ('iSaku', 'ewallet', 'smartphone', '#F7941E', 109),
  ('DOKU', 'ewallet', 'smartphone', '#FF6600', 110),
  -- Cash & Others
  ('Tunai', 'cash', 'banknote', '#9AB17A', 200),
  ('Dompet', 'cash', 'wallet', '#C3CC9B', 201),
  ('Celengan', 'savings', 'piggy-bank', '#81B29A', 300),
  ('Deposito', 'savings', 'landmark', '#3D405B', 301),
  ('Reksadana', 'investment', 'trending-up', '#7C3AED', 400),
  ('Saham', 'investment', 'bar-chart-3', '#00A650', 401),
  ('Obligasi', 'investment', 'file-text', '#00529C', 402),
  ('Emas', 'investment', 'coins', '#F2CC8F', 403),
  ('Crypto', 'investment', 'bitcoin', '#F7931E', 404);
